version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
  deploy:
    jobs:
      - docker/publish:
          image: midas80/docker-hy.github.io
          tag: 'latest'
